site_name: "mkdocs1" # Cambiado 2/9/2025
site_url: https://github.com/jav-car-1971/mkdocs1 # Cambiado 2/9/2025
repo_url: https://jav-car-1971.github.io/mkdocs1/ # Cambiado 2/9/2025
edit_uri: edit/main/docs # Se supone que va a funcionar, pero si tu rama principal se llama diferente.
# o si la carpeta de tu documentación tiene otro nombre, tenés que ajustarlo.

theme:
  name: material
  features:
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: amber
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# extra:                               # Elimine comentando todo este bloque por ahora
#  analytics:                          # Elimine comentando todo este bloque por ahora
#    provider: google                  # Elimine comentando todo este bloque por ahora
#    property: G-SZB618VNBZ            # Elimine comentando todo este bloque por ahora

plugins:
  - search
  - awesome-pages

extra_javascript:
  - https://unpkg.com/mermaid@8.5.0/dist/mermaid.min.js

extra_css:
  - https://use.fontawesome.com/releases/v5.13.0/css/all.css

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.smartsymbols
  - meta
  - toc:
      # insert a blank space before the character
      permalink: " ¶"
  - smarty
